# See the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "adidahiya"
    groups:
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
      postcss:
        patterns:
          - "postcss"
          - "postcss-*"
      stylelint:
        patterns:
          - "styelint"
          - "stylelint-*"
      test-infra:
        patterns:
          - "jest"
          - "@jest/*"
          - "ts-jest"
          - "karma",
          - "karma-*"
          - "mocha"
      webpack:
        patterns:
          - "webpack"
          - "webpack-*"
          - "*-webpack-*"
          - "*-loader"
      runtime-dependencies:
        dependency-type: "production"
      dev-dependencies:
        dependency-type: "development"
    ignore:
      # don't try to update internal packages
      - dependency-name: "@blueprintjs/*"
      # typescript and typedoc are usually upgraded together, and are often require code changes
      - dependency-name: "typescript"
      - dependency-name: "typedoc"
      # deprecated dependencies
      - dependency-name: "moment"
      - dependency-name: "moment-*"
      # we are stuck on svgo v1 for now
      # see https://github.com/palantir/blueprint/blob/727b91ffe76f49cded1acb8240c44502f34fce48/packages/icons/scripts/generate-icon-paths.mjs#L27-L30
      - dependency-name: "svgo"
      - dependency-name: "@types/svgo"
      # lodash hasn't released for >2 years
      - dependency-name: "lodash"
      # see https://github.com/tancredi/fantasticon/issues/470
      - dependency-name: "fantasticon"
